# Form implementation generated from reading ui file 'app\forms\forms.ui\create_procedure.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CreateProcedureWindow(object):
    def setupUi(self, CreateProcedureWindow):
        CreateProcedureWindow.setObjectName("CreateProcedureWindow")
        CreateProcedureWindow.resize(456, 234)
        self.centralwidget = QtWidgets.QWidget(parent=CreateProcedureWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.name_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.name_line.setObjectName("name_line")
        self.horizontalLayout_5.addWidget(self.name_line)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.price_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.price_line.setObjectName("price_line")
        self.horizontalLayout_6.addWidget(self.price_line)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.comment_plain_text = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.comment_plain_text.setObjectName("comment_plain_text")
        self.verticalLayout.addWidget(self.comment_plain_text)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.create_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.create_btn.setObjectName("create_btn")
        self.horizontalLayout.addWidget(self.create_btn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.cancel_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout.addWidget(self.cancel_btn)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        CreateProcedureWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(CreateProcedureWindow)
        QtCore.QMetaObject.connectSlotsByName(CreateProcedureWindow)

    def retranslateUi(self, CreateProcedureWindow):
        _translate = QtCore.QCoreApplication.translate
        CreateProcedureWindow.setWindowTitle(_translate("CreateProcedureWindow", "MainWindow"))
        self.label_5.setText(_translate("CreateProcedureWindow", "Название процедуры:"))
        self.label_7.setText(_translate("CreateProcedureWindow", "Цена:"))
        self.label_6.setText(_translate("CreateProcedureWindow", "Описание:"))
        self.create_btn.setText(_translate("CreateProcedureWindow", "Добавить"))
        self.cancel_btn.setText(_translate("CreateProcedureWindow", "Отмена"))
