# Form implementation generated from reading ui file 'app\forms\forms.ui\create_order.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CreateOrderWindow(object):
    def setupUi(self, CreateOrderWindow):
        CreateOrderWindow.setObjectName("CreateOrderWindow")
        CreateOrderWindow.resize(446, 361)
        self.centralwidget = QtWidgets.QWidget(parent=CreateOrderWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.data_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.data_label.setText("")
        self.data_label.setObjectName("data_label")
        self.verticalLayout_2.addWidget(self.data_label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.comment_plain_text = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.comment_plain_text.setObjectName("comment_plain_text")
        self.verticalLayout.addWidget(self.comment_plain_text)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.procedureBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.procedureBox.setMinimumSize(QtCore.QSize(100, 0))
        self.procedureBox.setObjectName("procedureBox")
        self.verticalLayout_2.addWidget(self.procedureBox)
        self.patientBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.patientBox.setMinimumSize(QtCore.QSize(100, 0))
        self.patientBox.setObjectName("patientBox")
        self.verticalLayout_2.addWidget(self.patientBox)
        self.user_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.user_label.setText("")
        self.user_label.setObjectName("user_label")
        self.verticalLayout_2.addWidget(self.user_label)
        self.price_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.price_label.setText("")
        self.price_label.setObjectName("price_label")
        self.verticalLayout_2.addWidget(self.price_label)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.create_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.create_btn.setObjectName("create_btn")
        self.horizontalLayout.addWidget(self.create_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.cancel_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout.addWidget(self.cancel_btn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        CreateOrderWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(CreateOrderWindow)
        QtCore.QMetaObject.connectSlotsByName(CreateOrderWindow)

    def retranslateUi(self, CreateOrderWindow):
        _translate = QtCore.QCoreApplication.translate
        CreateOrderWindow.setWindowTitle(_translate("CreateOrderWindow", "MainWindow"))
        self.label_6.setText(_translate("CreateOrderWindow", "Описание:"))
        self.create_btn.setText(_translate("CreateOrderWindow", "Добавить"))
        self.cancel_btn.setText(_translate("CreateOrderWindow", "Отмена"))
