# Form implementation generated from reading ui file 'app\forms\forms.ui\main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(751, 505)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.data_table = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.data_table.setObjectName("data_table")
        self.data_table.setColumnCount(0)
        self.data_table.setRowCount(0)
        self.data_table.horizontalHeader().setSortIndicatorShown(True)
        self.data_table.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout.addWidget(self.data_table)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.patients_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.patients_btn.setObjectName("patients_btn")
        self.verticalLayout.addWidget(self.patients_btn)
        self.create_patients_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.create_patients_btn.setObjectName("create_patients_btn")
        self.verticalLayout.addWidget(self.create_patients_btn)
        self.users_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.users_btn.setObjectName("users_btn")
        self.verticalLayout.addWidget(self.users_btn)
        self.create_users_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.create_users_btn.setObjectName("create_users_btn")
        self.verticalLayout.addWidget(self.create_users_btn)
        self.procedures_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.procedures_btn.setObjectName("procedures_btn")
        self.verticalLayout.addWidget(self.procedures_btn)
        self.create_procedures_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.create_procedures_btn.setObjectName("create_procedures_btn")
        self.verticalLayout.addWidget(self.create_procedures_btn)
        self.orders_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.orders_btn.setObjectName("orders_btn")
        self.verticalLayout.addWidget(self.orders_btn)
        self.create_orders_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.create_orders_btn.setObjectName("create_orders_btn")
        self.verticalLayout.addWidget(self.create_orders_btn)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.patients_btn.setText(_translate("MainWindow", "Пациенты"))
        self.create_patients_btn.setText(_translate("MainWindow", "Добавить пациента"))
        self.users_btn.setText(_translate("MainWindow", "Пользователи"))
        self.create_users_btn.setText(_translate("MainWindow", "Добавить пользователя"))
        self.procedures_btn.setText(_translate("MainWindow", "Процедуры "))
        self.create_procedures_btn.setText(_translate("MainWindow", "Создание процедуры"))
        self.orders_btn.setText(_translate("MainWindow", "Заказы"))
        self.create_orders_btn.setText(_translate("MainWindow", "Создание заказа"))
